version: "3.9"
services:
  ts-project:
    environment:
      - ENV=development
      - POSTGRES_HOST=127.0.0.1
      - POSTGRES_DB=electricitymap
      - POSTGRES_USER=postgres
      - EMAP_PROJECT_ID=tmrow-152415
    ports:
      - "8000:5000"
      - "5432:5432"
    build:
      context: .
      dockerfile: Dockerfile.local
    volumes:
      - .:/app
      - ~/.config/gcloud:/root/.config/gcloud
