steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build'
    args: ['build', '--no-cache', '-t',
           'eu.gcr.io/${PROJECT_ID}/mlops-ts-project-training:${SHORT_SHA}', '-f', 'src/model/Dockerfile.training', '.']

  # Test
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Test'
    args: ['run', '--rm', '--entrypoint', 'poetry', 'eu.gcr.io/${PROJECT_ID}/mlops-ts-project-training:${SHORT_SHA}', 'run', 'check_training']

  # Docker push to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push'
    args: ['push',  'eu.gcr.io/${PROJECT_ID}/mlops-ts-project-training:${SHORT_SHA}']

# Store images in Google Artifact Registry
images:
  - eu.gcr.io/${PROJECT_ID}/mlops-ts-project-training:${SHORT_SHA}

timeout: 3600s